# Generated by Django 4.2.7 on 2023-11-07 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peprclip', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peprclip_function',
            name='function_name',
            field=models.CharField(max_length=100),
        ),
    ]
